### PR TITLE
PHP Error Log - empty value

### PR DESCRIPTION
**Pull request by dnicinski**
Hi Curtiss,  The error log is getting spammed with these two PHP warnings. Can you push a fix for these please? Thanks!

`Creating default object from empty value in /var/www/html/wp-content/plugins/post-content-shortcodes/classes/class-post-content-shortcodes.php on **line 970**`
Creating` default object from empty value in /var/www/html/wp-content/plugins/post-content-shortcodes/classes/class-post-content-shortcodes.php on **line 988**`

### CODE REVIEW

**Comment by cgrymala** [comment]
@dnicinski Are you able to confirm which version you're using and where you got it from? I'm not seeing anything in any of the versions that correspond to the error message about line 988, and I want to be sure about what I'm fixing before I dig too deeply into it; especially because I am actively working on re-building this plugin to natively support the Block Editor. Thanks.

**Comment by dnicinski** [comment]
Hi @cgrymala  We are using 1.0.1.2 in a multisite install.  We got it from this repo years ago. 

Post Content Shortcodes  
**Network Deactivate**
Adds shortcodes to show the content of another post or to show a list of posts 						
Version 1.0.1.2 | By cgrymala

**Comment by dnicinski** [comment]
Hi @cgrymala, Any luck yet?

**Comment by cgrymala** [comment]
@dnicinski This tag should fix the issue: https://github.com/cgrymala/post-content-shortcodes/releases/tag/1.0.1.2.1

**Pull request closed without merging**
